name = "lisbeth-hamlin-worker"
workers_dev = true
compatibility_date = "2022-06-05"
kv_namespaces = [
  { binding = "LISBETH_HAMLIN", id = "6d03f407f6c44f2ba6688ef53dcc1eb4", preview_id = "6d03f407f6c44f2ba6688ef53dcc1eb4" }
]

[env.production]
kv_namespaces = [
  { binding = "LISBETH_HAMLIN", id = "f65e4d7d9cc14a5c8742c970491a7e1e" }
]
routes = ["https://worker.lisbethhamlin.com/*"]
workers_dev = false

[build.upload]
format = "modules"
dir = "./dist"
main = "./worker.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[build]
command = "npm ci && npm run build"
