name: Build
on:
  push:
    branches:
      - main
  repository_dispatch:
jobs:
    deploy:
      runs-on: ubuntu-latest
      timeout-minutes: 15
      # needs: test
      steps:
        - uses: actions/checkout@v3
        - name: Publish to dev
          uses: cloudflare/wrangler-action@2.0.0
          with:
            apiToken: ${{ secrets.CF_API_TOKEN }}
            command: publish
          env:
            CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        - name: Publish
          uses: cloudflare/wrangler-action@2.0.0
          with:
            apiToken: ${{ secrets.CF_API_TOKEN }}
            command: publish --env production
          env:
            CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
